### ISSUE TITLE
Incorrect name of template

### ISSUE THREAD

**Issue by thsutton** [aristotle-mdr/aristotle-dataset-extensions#10]
`aristotle_dse/templates/aristotle_dse/concepts/dataSource.html` contains a path to a template which does not exist in `aristotle_mdr`:

```
{% extends "aristotle_mdr/managedContent.html" %}
```

Here's an example page demonstration the failure

http://aristotle.pythonanywhere.com/item/602880/datasource/yellow-pages

**Comment by LegoStormtroopr** [comment]
Thanks for the pick up. 
I'll fix this this weekend. There is an issue in the test runner with XHTML2PDF importing a too new version of a lib.
